#define NODES(V) \
  V(IdentifierNode)\
  V(NullLiteralNode)\
  V(StringLiteralNode)\
  V(BooleanLiteralNode)\
  V(NumericLiteralNode)\
  V(UnaryExpressionNode)\
  V(BinaryExpressionNode)\
  V(ExpressionStatementNode)\
  V(BlockStatementNode)\
  V(DebuggerStatementNode)\
  V(EmptyStatementNode)\
  V(ReturnStatementNode)\
  V(ContinueStatementNode)\
  V(BreakStatementNode)\
  V(IfStatementNode)\
  V(SwitchStatementNode)\
  V(SwitchCaseNode)\
  V(WhileStatementNode)\
  V(DoWhileStatementNode)\
  V(ForStatementNode)\
  V(VariableDeclarationNode)\
  V(VariableDeclaratorNode)\
  V(ForInStatementNode)\
  V(ForOfStatementNode)\
  V(ThrowStatementNode)\
  V(CatchClauseNode)\
  V(TryStatementNode)\
  V(FunctionDeclarationNode)\
  V(FunctionExpressionNode)\
  V(ProgramNode)\
  V(ImportDeclarationNode)\
  V(ImportSpecifierNode)\
  V(ImportDefaultSpecifierNode)\
  V(ImportNamespaceSpecifierNode)\
  V(ExportSpecifierNode)\
  V(ExportDefaultSpecifierNode)\
  V(ExportNamespaceSpecifierNode)\
  V(ExportNamedDeclarationNode)\
  V(ExportDefaultDeclarationNode)\
  V(ExportAllDeclarationNode)\
  V(CallExpressionNode)\
  V(ParenthesizedExpressionNode)\
